### ISSUE TITLE
Uploading from the homepage silently fails

### ISSUE THREAD

**Issue by ybizeul** [EnjoyBacon7/cbFiles#2]
When uploading directly from the home page, the upload is stuck in undefined progress bar and the server logs :
```
Chunk upload request received :
 The share does not exist, creation is done from Home page. Canceling upload
```

There should be an indication that a share needs to be created first and the upload box hidden/disabled

**Comment by EnjoyBacon7** [comment]
Making a clean install and uploading a file from the home page works just as intended for me. Could you provide more steps to recreate the problem?

**Comment by EnjoyBacon7** [comment]
main branch currently does not support uploading. Please pull from Early-Release.
